### ISSUE TITLE
无法启动项目

### ISSUE THREAD

**Issue by xiaoMingLong** [zhuo-zx/testOL#2]
![image](https://user-images.githubusercontent.com/91582283/180744228-cb2a4392-3804-42d5-a679-184356a27239.png)

node 16.15.1
node 14.19.3 无法启动项目

**Comment by zhuo-zx** [comment]
你这个是ol版本的问题，修改一下ol/source的引用方式就可以了
import { OSM, XYZ } from 'ol/source';
改成
import OSM from 'ol/source/OSM';
import XYZ from 'ol/source/XYZ';

如此类推，全局搜一下
